### ISSUE TITLE
마크다운보다는 데이터로 관리가 되면 더 좋을 것 같습니다.

### ISSUE THREAD

**Issue by kkweon** [taeoh-kim/pr12#2]
yaml 파일로 관리하고 거기서 자동으로 generate 하는게 유지보수 하는 편에서 훨씬 수월할 것 같습니다.

```yaml
- id: 2
  title: Deformable Convolutional Networks
  papers:
    - title: first paper
      link: https://arxiv.org/abs/1703.06211
      authors: [ ... ]

    - title: second paper
      link: ...
  video:
    link: https://youtu.be/RRwaz0fBQ0Y
  presenter: Terry TaeWoong Um
  keywords: [ ... ]

- id: 3
  ...
```
